### ISSUE TITLE
file type error omegaconf

### ISSUE THREAD

**Issue by RuchaCB** [AryanShekarlaban/data2vec-pytorch#15]
getting the following error 

Traceback (most recent call last):
  File "c:/Users/{}/Downloads/data2vec-pytorch-main/data2vec-pytorch-main/train.py", line 15, in <module>
    cfg = omegaconf.OmegaConf.load(cfg_path)
  File "C:\Program Files\Python38\lib\site-packages\omegaconf\omegaconf.py", line 194, in load
    raise TypeError("Unexpected file type")
TypeError: Unexpected file type

do we need to change anything in here?
cfg = omegaconf.OmegaConf.load(cfg_path)

**Comment by arxyzan** [comment]
Hello @RuchaCB 
How did you run this file? 
Did you run it by passing `--config` parameter like so `python train.py --config /path/to/config.yaml`?
You can simply put a print before the line you mentioned to see what path you're passing.
